name: albiruni_fetcher
description: Fetch albiruni data and store to DB
version: 1.0.0
repository: https://github.com/iqfareez/albiruni_fetcher

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  args: ^2.4.0
  albiruni: ^1.2.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
